import Head from "next/head";

import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import data from "./data.json";

import TopBar from "@/components/topBar/TopBar";
import PlanetTab from "@/components/planetTab/PlanetTab";
import getPlanetNames from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ planets }) {
  //console.log("data::", data);
  // const planets = data.map((planet, key={}) => planet.name);
  // console.log("index.js - props:", props);
  console.log(
    "planets:",
    planets.map((planet) => planet.fields.planetField)
  );

  const objects = data.map((planet) => {
    return { name: planet.name, color: planet.color };
  });
  console.log("const obj::", objects);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TopBar />

        <nav className={styles.menu}>
          {planets.map((planet) => (
            <PlanetTab key={planet} planet={planet.fields.planetField}>
              {" "}
            </PlanetTab>
          ))}
        </nav>
      </main>
    </>
  );
}

// export async function getStaticProps(context) {
//   const planets = data.map((planet) => planet.name + planet.color);
//   return {
//     props: {
//       planets: planets,
//     },
//   };
// }

Home.getInitialProps = async () => {
  const planets = await getPlanetNames();

  return { planets };
};
