import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import data from "./data.json";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  //console.log("data::", data);
  // const planets = data.map((planet, key={}) => planet.name);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello Planets!</h1>
        <nav>
          {props.planets.map((planet) => (
            <Link key={planet} href={`/planets/${planet}`}>
              <button>{planet}</button>
            </Link>
          ))}
        </nav>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const planets = data.map((planet) => planet.name);
  return {
    props: {
      planets: planets,
    },
  };
}
